resources:
- clusterrole.yaml
- cluster-role-binding.yaml
- backend-deployment.yaml
- frontend-deployment.yaml
- backend-service.yaml
- frontend-service.yaml
- backend-ingress.yaml
- frontend-ingress.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: backend
  newName: quay.io/kryanbeane/kueueviz-backend
  newTag: v0.14.0-devel-232-gf7a52aaf5-dirty
- name: frontend
  newName: quay.io/kryanbeane/kueueviz-frontend
  newTag: v0.14.0-devel-232-gf7a52aaf5-dirty
